# version: '3'
# services:
#   db:
#     image: mysql:8.0
#     container_name: mysql_baru
#     environment:
#       MYSQL_ROOT_PASSWORD: admin123
#       MYSQL_DATABASE: klastering_siswa
#       MYSQL_USER: admin
#       MYSQL_PASSWORD: admin123
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./klastering_siswa (2).sql:/docker-entrypoint-initdb.d/init.sql
#     command: --default-authentication-plugin=mysql_native_password

# volumes:
#   db_data:

version: '3.7'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: host.docker.internal  # Menghubungkan ke MySQL di host (Mac)
      PMA_USER: admin  # Ganti dengan user MySQL Anda
      PMA_PASSWORD: admin123  # Ganti dengan password MySQL Anda
    ports:
      - "8080:80"  # Akses phpMyAdmin lewat port 8080
    networks:
      - phpmyadmin-network

networks:
  phpmyadmin-network:
    driver: bridge
